# Generated by Django 5.1.7 on 2025-04-08 15:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Названия поста')),
                ('description', models.CharField(max_length=5000, verbose_name='Описания')),
                ('data_publication', models.DateTimeField(default=datetime.datetime(2025, 4, 8, 15, 23, 46, 59044, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации')),
                ('likes', models.PositiveBigIntegerField(default=0, verbose_name='лайки')),
                ('dislikes', models.PositiveBigIntegerField(default=0, verbose_name='дизлайки')),
                ('user', models.ForeignKey(default='Unknown author', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='client_posts', to='clients.client', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaage', models.ImageField(upload_to='images/posts/', verbose_name='изоброжения')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='posts.posts', verbose_name='статья')),
            ],
        ),
    ]
