# Generated by Django 5.1.7 on 2025-04-08 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='data_publication',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 16, 12, 9, 578113, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
