# Generated by Django 5.1.7 on 2025-04-14 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_posts_data_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='imaage',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='posts',
            name='data_publication',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 14, 40, 24, 407093, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
