# Generated by Django 5.1.7 on 2025-04-14 15:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_images_options_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post_categories', to='posts.posts', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='posts.posts', verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='data_publication',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 15, 28, 13, 53438, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
