# Generated by Django 5.1.7 on 2025-04-14 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_categories_post_alter_images_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='data_publication',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 15, 32, 22, 537946, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
