# Generated by Django 5.1.7 on 2025-04-14 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_images_post_alter_posts_data_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='data_publication',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
