# Generated by Django 5.1.7 on 2025-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_posts_data_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='post',
        ),
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.ManyToManyField(related_name='post_categories', to='posts.categories', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Категория'),
        ),
    ]
