# Generated by Django 5.1.7 on 2025-05-04 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_categories_post_posts_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='users_disliked',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие дизлайк'),
        ),
        migrations.AddField(
            model_name='posts',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие лайк'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Описания'),
        ),
    ]
