# Generated by Django 5.1.7 on 2025-04-14 14:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='ФИО Автора')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст')),
                ('likes', models.PositiveBigIntegerField(default=0, verbose_name='лайки')),
                ('dislikes', models.PositiveBigIntegerField(default=0, verbose_name='дизлайки')),
                ('data_coments', models.DateTimeField(default=datetime.datetime(2025, 4, 14, 14, 24, 48, 923356, tzinfo=datetime.timezone.utc), verbose_name='Дата коментарии')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comments', verbose_name='Родительский комментарий')),
            ],
        ),
    ]
