# Generated by Django 5.1.7 on 2025-04-14 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='data_coments',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 14, 40, 24, 400768, tzinfo=datetime.timezone.utc), verbose_name='Дата коментарии'),
        ),
    ]
