# Generated by Django 5.1.7 on 2025-05-04 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_alter_comments_data_coments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='data_coments',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 9, 2, 39, 470652, tzinfo=datetime.timezone.utc), verbose_name='Дата коментарии'),
        ),
    ]
